### ISSUE TITLE
Error when uploading certain apps

### ISSUE THREAD

**Issue by auanasgheps** [tbwfdu/fetch#2]
Hi there,

Testing 0.4.0.

Most applications do get uploaded, but some don't, like Chrome and PuTTY.

![immagine](https://github.com/user-attachments/assets/c2ff4e0e-8c70-4d14-a007-45146b629acc)

I tried removing the installers from the folder

The logs are not being refreshed. From a previous attempt:

```
2024-09-18 17:09:49.139 +02:00 [VRB] AutoSuggestBox Item Selected: Google Chrome
2024-09-18 17:09:49.153 +02:00 [VRB] Packages Found 1
2024-09-18 17:09:49.157 +02:00 [VRB] Installers Found 1
2024-09-18 17:09:49.157 +02:00 [VRB] [AppSearchPage] VersionComboBox_OnSelectionChanged
2024-09-18 17:09:49.166 +02:00 [VRB] [AppSearchPage] packageId: Google.Chrome, version: 128.0.6613.138, allVersions: 1, allInstallers: 1
2024-09-18 17:09:49.166 +02:00 [VRB] [AppSearchPage] currentPackage: Fetch.Models.Package, currentInstaller: Fetch.Models.Installer
2024-09-18 17:09:50.529 +02:00 [VRB] [AppSearchPage] --> ConfirmProceedDialog_ProceedButtonClick
2024-09-18 17:09:50.529 +02:00 [INF] [AppSearchPage] Adding Google Chrome to Queue
2024-09-18 17:09:50.529 +02:00 [VRB] [AppSearchPage] _package: Fetch.Models.Package, _version_: 128.0.6613.138 _type: msi, _architecture: x64
2024-09-18 17:09:50.529 +02:00 [VRB] [AppSearchPage] foundList: 0
2024-09-18 17:09:50.533 +02:00 [VRB] [AppSearchPage] installersList: 1
2024-09-18 17:09:50.533 +02:00 [VRB] [AppSearchPage] _switches: Fetch.Models.InstallerSwitches, _silentParam:  _filename: googlechromestandaloneenterprise64.msi, _extension: .msi
2024-09-18 17:09:50.533 +02:00 [VRB] [AppSearchPage] Generated NativeApp: Fetch.Models.UemNativeApp
2024-09-18 17:09:50.538 +02:00 [VRB] [AppSearchPage] VersionComboBox_OnSelectionChanged
2024-09-18 17:09:50.538 +02:00 [VRB] [AppSearchPage] ViewModel.SelectedPackage.PackageIdentifier null
2024-09-18 17:09:50.544 +02:00 [VRB] [SearchApplications] --> UpdateUI
2024-09-18 17:09:51.519 +02:00 [INF] [AppSearchPage] User confirmation requested
2024-09-18 17:09:52.566 +02:00 [VRB] [AppSearchPage] --> ConfirmProceedDialog_ProceedButtonClick
2024-09-18 17:09:52.566 +02:00 [INF] [AppSearchPage] User confirmation confirmed
2024-09-18 17:09:52.566 +02:00 [INF] [AppSearchPage] Apps in Queue: 1
2024-09-18 17:09:53.073 +02:00 [VRB] [AppSearchPage] --> Go_OnClick
2024-09-18 17:09:53.073 +02:00 [INF] [AppSearchPage] Initiating Processing of Queue
2024-09-18 17:09:53.183 +02:00 [VRB] [SearchApplications] --> UpdateUI
2024-09-18 17:09:53.184 +02:00 [VRB] [AppSearchPage] --> SelectorBar_OnSelectionChanged
2024-09-18 17:09:53.185 +02:00 [INF] [AppSearchPage] Downloads to Process: 1
2024-09-18 17:09:53.186 +02:00 [INF] [AppSearchPage] Downloading Google Chrome
2024-09-18 17:09:53.187 +02:00 [INF] [AppSearchPage] Creating Path: C:\Temp\FetchDownloads\Google.Chrome\128.0.6613.138\x64
2024-09-18 17:09:53.187 +02:00 [INF] [AppSearchPage] Installer previously downloaded
2024-09-18 17:09:55.188 +02:00 [INF] [AppSearchPage] Starting Installer Upload
2024-09-18 17:09:55.188 +02:00 [INF] [AppSearchPage] Uploading MSI File
2024-09-18 17:09:55.188 +02:00 [VRB] [AppSearchPage] --> CreateFileBlobAsChunkAsync
2024-09-18 17:09:55.189 +02:00 [VRB] Existing Token Still Valid
2024-09-18 17:09:55.189 +02:00 [VRB] [AppSearchPage] --> ChunkFileAsync
2024-09-18 17:09:55.189 +02:00 [VRB] [AppSearchPage] totalChunks: 1
2024-09-18 17:09:55.189 +02:00 [VRB] [AppSearchPage] --> SendChunkRequestAsync
2024-09-18 17:09:55.555 +02:00 [VRB] [AppSearchPage] SendChunkRequestAsync: Chunk 1 of 1
2024-09-18 17:09:55.555 +02:00 [VRB] [AppSearchPage] transactionId: 95ab054d-f316-4a26-a7c9-2677f2387536
2024-09-18 17:09:55.555 +02:00 [VRB] [AppSearchPage] Transaction ID: 95ab054d-f316-4a26-a7c9-2677f2387536
2024-09-18 17:09:55.556 +02:00 [INF] [AppSearchPage] Upload Complete.
2024-09-18 17:09:56.061 +02:00 [INF] [AppSearchPage] Creating Application in App Catalog
2024-09-18 17:09:56.061 +02:00 [VRB] [Tools] --> CreateApplicationByTransactionIdAsync
2024-09-18 17:09:56.062 +02:00 [VRB] Existing Token Still Valid
2024-09-18 17:09:56.062 +02:00 [VRB] [Tools] AppCreationBody: {
  "transaction_id": "95ab054d-f316-4a26-a7c9-2677f2387536",
  "application_name": "Google Chrome",
  "device_type": 12,
  "supported_models": {
    "model": [
      {
        "model_id": 83,
        "model_name": "Desktop"
      }
    ]
  },
  "push_mode": 0,
  "description": "The Fast & Secure Web Browser Built to be Yours",
  "auto_update_version": false,
  "organization_group_uuid": "84385785-598e-499f-bd62-d38f36558436",
  "enable_provisioning": false,
  "upload_via_link": false,
  "app_uem_version": "128.0.6613.138",
  "file_name": "googlechromestandaloneenterprise64.msi",
  "supported_processor_architecture": "x64",
  "dependency_file": false,
  "deployment_options": {
    "when_to_install": {
      "data_contingencies": [],
      "disk_space_required_in_kb": 10240,
      "device_power_required": 10,
      "ram_required_in_mb": 50,
      "cpu_usage": 0
    },
    "how_to_install": {
      "install_context": 1,
      "install_command": "msiexec /i \"googlechromestandaloneenterprise64.msi\" /qn",
      "admin_privileges": true,
      "device_restart": 1,
      "retry_count": 3,
      "retry_interval_in_minutes": 6,
      "installer_reboot_exit_code": "3010",
      "installer_success_exit_code": "0",
      "restart_deadline_in_days": 0
    },
    "when_to_call_install_complete": {
      "use_additional_criteria": false
    }
  },
  "files_options": {
    "app_dependencies_list": [],
    "app_transform_list": [],
    "app_patches_list": [],
    "application_uninstall_process": {
      "use_custom_script": false
    }
  },
  "carryover_assignments": true,
  "application_source": 1,
  "category_list": {
    "category": []
  },
  "ear_app_update_mode": 0,
  "internal_id": "fetch_autoupdate"
}
2024-09-18 17:09:57.554 +02:00 [VRB] [Tools] Create App Result: {
  "errorCode": 400,
  "message": "Invalid BlobId.",
  "activityId": "e04bde96-65a4-45eb-a04e-1aa8965b20d6"
}
2024-09-18 17:09:57.554 +02:00 [INF] [AppSearchPage] Upload Success: False
2024-09-18 17:09:57.554 +02:00 [VRB] [AppSearchPage] {
  "errorCode": 400,
  "message": "Invalid BlobId.",
  "activityId": "e04bde96-65a4-45eb-a04e-1aa8965b20d6"
```

**Comment by TroyLambert-CoP** [comment]
I am having the same issue with Adobe AIR version 51.1.1.3. I did a check of the logs, and found an error. Here is the portion of the log file:

-09-27 09:26:08.097 -07:00 [VRB] AutoSuggestBox Item Selected: Adobe AIR
2024-09-27 09:26:08.108 -07:00 [VRB] Packages Found 1
2024-09-27 09:26:08.116 -07:00 [VRB] Installers Found 1
2024-09-27 09:26:08.116 -07:00 [VRB] [AppSearchPage] VersionComboBox_OnSelectionChanged
2024-09-27 09:26:08.120 -07:00 [VRB] [AppSearchPage] packageId: HARMAN.AdobeAIR, version: 51.1.1.3, allVersions: 1, allInstallers: 1
2024-09-27 09:26:08.120 -07:00 [VRB] [AppSearchPage] currentPackage: Fetch.Models.Package, currentInstaller: Fetch.Models.Installer
2024-09-27 09:26:20.365 -07:00 [VRB] [AppSearchPage] --> ConfirmProceedDialog_ProceedButtonClick
2024-09-27 09:26:20.365 -07:00 [INF] [AppSearchPage] Adding Adobe AIR to Queue
2024-09-27 09:26:20.365 -07:00 [VRB] [AppSearchPage] _package: Fetch.Models.Package, _version_: 51.1.1.3 _type: exe, _architecture: x86
2024-09-27 09:26:20.365 -07:00 [VRB] [AppSearchPage] foundList: 0
2024-09-27 09:26:20.376 -07:00 [VRB] [AppSearchPage] installersList: 1
2024-09-27 09:26:20.376 -07:00 [VRB] [AppSearchPage] _switches: Fetch.Models.InstallerSwitches, _silentParam: -silent _filename: AdobeAIR.exe, _extension: .exe
2024-09-27 09:26:20.376 -07:00 [VRB] [AppSearchPage] Generated NativeApp: Fetch.Models.UemNativeApp
2024-09-27 09:26:20.380 -07:00 [VRB] [AppSearchPage] VersionComboBox_OnSelectionChanged
2024-09-27 09:26:20.380 -07:00 [VRB] [AppSearchPage] ViewModel.SelectedPackage.PackageIdentifier null
2024-09-27 09:26:20.380 -07:00 [VRB] [AppSearchPage] VersionComboBox_OnSelectionChanged
2024-09-27 09:26:20.380 -07:00 [VRB] [AppSearchPage] ViewModel.SelectedPackage.PackageIdentifier null
2024-09-27 09:26:20.385 -07:00 [VRB] [SearchApplications] --> UpdateUI
2024-09-27 09:26:26.280 -07:00 [INF] [AppSearchPage] User confirmation requested
2024-09-27 09:26:28.997 -07:00 [VRB] [AppSearchPage] --> ConfirmProceedDialog_ProceedButtonClick
2024-09-27 09:26:28.997 -07:00 [INF] [AppSearchPage] User confirmation confirmed
2024-09-27 09:26:28.997 -07:00 [INF] [AppSearchPage] Apps in Queue: 1
2024-09-27 09:26:29.512 -07:00 [VRB] [AppSearchPage] --> Go_OnClick
2024-09-27 09:26:29.512 -07:00 [INF] [AppSearchPage] Initiating Processing of Queue
2024-09-27 09:26:29.622 -07:00 [VRB] [SearchApplications] --> UpdateUI
2024-09-27 09:26:29.623 -07:00 [VRB] [AppSearchPage] --> SelectorBar_OnSelectionChanged
2024-09-27 09:26:29.624 -07:00 [INF] [AppSearchPage] Downloads to Process: 1
2024-09-27 09:26:29.624 -07:00 [INF] [AppSearchPage] Downloading Adobe AIR
2024-09-27 09:26:29.624 -07:00 [INF] [AppSearchPage] Creating Path: C:\Temp\FetchDownloads\HARMAN.AdobeAIR\51.1.1.3\x86
2024-09-27 09:26:29.624 -07:00 [INF] [AppSearchPage] Download Started: https://airsdk.harman.com/assets/downloads/AdobeAIR.exe
2024-09-27 09:26:29.998 -07:00 [ERR] [AppSearchPage] --> DownloadWithStatus
2024-09-27 09:26:29.999 -07:00 [ERR] [AppSearchPage] Error Code: NotFound, Reason: 
2024-09-27 09:26:29.999 -07:00 [ERR] [AppSearchPage] Download Failed: https://airsdk.harman.com/assets/downloads/AdobeAIR.exe
2024-09-27 09:26:31.998 -07:00 [VRB] [AppSearchPage] --> RemoveFromQueueAndResults
2024-09-27 09:26:31.998 -07:00 [VRB] [AppSearchPage] guid: 12ef2cc1-5b85-4e91-98f8-22fb772ea7b6
2024-09-27 09:26:31.999 -07:00 [VRB] [SearchApplications] --> UpdateUI
2024-09-27 09:26:32.000 -07:00 [VRB] [SearchApplications] --> UpdateUI
2024-09-27 09:26:39.355 -07:00 [VRB] [Settings] --> OnNavigatedTo
2024-09-27 09:26:39.357 -07:00 [VRB] [Settings] _getAppUpdatesOnStartup: 
2024-09-27 09:26:39.391 -07:00 [VRB] [SettingsPage] --> SettingsPage_Loaded
2024-09-27 09:26:39.397 -07:00 [VRB] [SettingsPage] --> VerboseLoggingToggle_OnToggledAsync
2024-09-27 09:26:42.790 -07:00 [VRB] [SettingsPage] --> ViewLogsButton_OnClick

I checked the link, and the correct path is shown here:
![image](https://github.com/user-attachments/assets/e1328295-4d75-4fd2-ab3c-002dc798df99)

**Comment by tbwfdu** [comment]
This should be resolved in the latest release (v0.5.0). This was most likely due to an issue where Fetch only uploaded to Customer Type OGs

**Comment by auanasgheps** [comment]
Hey, thanks for the update! Looks very nice.

I installed it but I'm still facing intermittent issues without a clear error. 
I tried to upload these apps and they always fail. Others works, but it's hit or miss.

Logs mention: `Invalid BlobId`

![immagine](https://github.com/user-attachments/assets/978f28d3-c45a-4e88-a13b-c6ec9dee1a63)


[log20241014.txt](https://github.com/user-attachments/files/17366569/log20241014.txt)

**Comment by auanasgheps** [comment]
Ok, I deleted all installers in C:\Temp\FetchDownloads and Chrome was uploaded successfully.

KeePass is not being downloaded. That's fine, It might be an external server issue, but Fetch should catch this and maybe offer an option to retry.
